from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pytest

from egosieve.training.augmentation import (
    MANIFEST_SCHEMA,
    PROVENANCE_SCHEMA,
    TRANSFORM_TO_ISSUE,
    AugmentationConfig,
    AugmentationError,
    build_augmented_corpus,
)
from egosieve.training.data import ISSUE_LABELS, SCHEMA_VERSION, load_jsonl
from egosieve.video import probe_video, sha256_file

FFMPEG = shutil.which("ffmpeg")
FFPROBE = shutil.which("ffprobe")
pytestmark = pytest.mark.skipif(
    FFMPEG is None or FFPROBE is None,
    reason="ffmpeg and ffprobe are required for augmentation fixtures",
)


def _make_source(path: Path, *, duration: float = 2.5) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            str(FFMPEG),
            "-nostdin",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            f"testsrc2=size=96x64:rate=12:duration={duration}",
            "-an",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-threads",
            "1",
            "-map_metadata",
            "-1",
            "-y",
            str(path),
        ],
        check=True,
        capture_output=True,
        shell=False,
    )


def _write_annotations(
    root: Path,
    *,
    license_name: str = "CC0-1.0",
    hand_regions: bool = True,
) -> Path:
    _make_source(root / "videos" / "source.mp4")
    window: dict[str, object] = {
        "start_s": 0.0,
        "end_s": 2.0,
        "issues": {"no_hands": False},
        "issue_valid": {"no_hands": True},
        "annotator": "human-reviewer-a",
        "label_provenance": {
            "readiness": {"kind": "unlabeled"},
            "issues": {"kind": "human"},
            "boundaries": {"kind": "unlabeled"},
        },
        "review_count": 2,
        "rubric_version": "fixture/v1",
    }
    if hand_regions:
        window["hand_regions"] = [[0.20, 0.35, 0.22, 0.35], [0.58, 0.35, 0.22, 0.35]]
    record = {
        "schema": SCHEMA_VERSION,
        "id": "synthetic-source-001",
        "group_id": "synthetic-session-001",
        "video": "videos/source.mp4",
        "license": license_name,
        "windows": [window],
        "split": "train",
        "dataset": "offline-generated-fixture",
        "dataset_revision": "fixture-v1",
        "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
        "attribution": "Generated by the test suite with FFmpeg testsrc2.",
    }
    path = root / "source.jsonl"
    path.write_text(json.dumps(record, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def _decoded_frames(path: Path) -> list[np.ndarray]:
    av = pytest.importorskip("av")
    with av.open(str(path)) as container:
        return [frame.to_ndarray(format="rgb24") for frame in container.decode(video=0)]


def _gradient_energy(frame: np.ndarray) -> float:
    values = frame.astype(np.float32)
    return float(np.abs(np.diff(values, axis=0)).mean() + np.abs(np.diff(values, axis=1)).mean())


def _provenance_by_transform(path: Path) -> dict[str, dict]:
    rows = _read_jsonl(path)
    return {row["transformation"]["name"]: row for row in rows}


def test_builder_emits_positive_only_proxies_with_complete_provenance(tmp_path: Path) -> None:
    annotations = _write_annotations(tmp_path)
    output = tmp_path / "derived"

    result = build_augmented_corpus(
        annotations,
        output,
        allowed_licenses=["CC0-1.0"],
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )

    assert result.generated_count == 6
    assert result.skipped_count == 2
    assert set(TRANSFORM_TO_ISSUE.values()) == set(ISSUE_LABELS)
    records = load_jsonl(result.annotations_path)
    assert len(records) == 6
    assert {record.extra["augmentation"]["transform"] for record in records} == {
        "blur",
        "exposure",
        "camera_instability",
        "freeze",
        "scene_cut",
        "hand_occlusion",
    }
    for record in records:
        assert record.group_id == "synthetic-session-001"
        assert record.license == "CC0-1.0"
        assert record.extra["split"] == "train"
        assert record.extra["dataset_revision"] == "fixture-v1"
        assert len(record.windows) == 1
        window = record.windows[0]
        assert window.readiness is None
        assert window.readiness_valid is False
        assert window.boundary_valid is False
        assert list(window.issues.values()) == [True]
        assert list(window.issue_valid.values()) == [True]
        assert set(window.issues) == set(window.issue_valid)
        assert window.annotator == "controlled-corruption:egosieve.augmentation/v1"
        label_provenance = window.extra["label_provenance"]
        assert label_provenance["readiness"] == {"kind": "unlabeled"}
        assert label_provenance["issues"]["kind"] == ("programmatic-controlled-corruption")
        assert label_provenance["issues"]["positive_only"] is True
        assert label_provenance["boundaries"] == {"kind": "unlabeled"}
        assert label_provenance["source_review"] == {
            "review_count": 2,
            "rubric_version": "fixture/v1",
        }
        assert "review_count" not in window.extra
        assert "rubric_version" not in window.extra
        target = next(iter(window.issues))
        assert target in ISSUE_LABELS
        assert all(name not in window.issue_valid for name in set(ISSUE_LABELS) - {target})
        media = output / record.video
        assert media.is_file()
        assert probe_video(media, ffprobe_bin=str(FFPROBE)).duration_s > 0

    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert manifest["schema"] == MANIFEST_SCHEMA
    assert manifest["counts"]["generated"] == 6
    assert manifest["label_policy"]["kinds"] == {"programmatic-controlled-corruption": 6}
    assert manifest["label_policy"]["unknown_issues_are_negative"] is False
    assert manifest["label_policy"]["source_inherited_issues"] == [
        "no_hands",
        "low_hand_activity",
    ]
    assert manifest["split_policy"]["group_id_preserved"] is True
    assert manifest["licensing"]["allowed_licenses"] == ["CC0-1.0"]
    assert manifest["tools"]["ffmpeg"]["binary_sha256"]
    assert manifest["tools"]["ffmpeg"]["version_line"].startswith("ffmpeg version")
    assert manifest["artifacts"]["annotations"]["sha256"] == sha256_file(result.annotations_path)
    assert manifest["source_annotations"] == {
        "path": str(annotations.resolve()),
        "sha256": sha256_file(annotations),
        "record_count": 1,
        "window_count": 1,
    }
    assert (
        manifest["source_annotations"]["sha256"] != manifest["artifacts"]["annotations"]["sha256"]
    )

    provenance = _read_jsonl(result.provenance_path)
    assert len(provenance) == 6
    for row in provenance:
        assert row["schema"] == PROVENANCE_SCHEMA
        assert row["source"]["group_id"] == "synthetic-session-001"
        assert row["source"]["split"] == "train"
        assert row["source"]["license"] == "CC0-1.0"
        assert row["source"]["label_summary"]["task_kinds"] == {
            "readiness": "unlabeled",
            "issues": "human",
            "boundaries": "unlabeled",
        }
        assert row["transformation"]["label_kind"] == ("programmatic-controlled-corruption")
        assert row["transformation"]["positive_only"] is True
        assert row["command"]["shell"] is False
        assert row["command"]["argv"][0] == str(Path(FFMPEG).resolve())
        assert "-noautorotate" in row["command"]["argv"]
        assert row["command"]["display"]
        derived = output / row["output"]["path"]
        assert row["output"]["sha256"] == sha256_file(derived)

    skipped = _read_jsonl(result.skipped_path)
    assert {row["transform"] for row in skipped} == {"no_hands", "low_hand_activity"}
    assert {row["code"] for row in skipped} == {"source_positive_required"}


def test_transforms_have_observable_evidence(tmp_path: Path) -> None:
    annotations = _write_annotations(tmp_path)
    output = tmp_path / "derived"
    result = build_augmented_corpus(
        annotations,
        output,
        allowed_licenses="CC0-1.0",
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )
    by_transform = _provenance_by_transform(result.provenance_path)
    source_frames = _decoded_frames(tmp_path / "videos" / "source.mp4")
    blur_frames = _decoded_frames(output / by_transform["blur"]["output"]["path"])
    exposure_frames = _decoded_frames(output / by_transform["exposure"]["output"]["path"])
    freeze_frames = _decoded_frames(output / by_transform["freeze"]["output"]["path"])
    occluded_frames = _decoded_frames(output / by_transform["hand_occlusion"]["output"]["path"])

    assert _gradient_energy(blur_frames[0]) < _gradient_energy(source_frames[0])
    assert exposure_frames[0].mean() < source_frames[0].mean() * 0.8
    frame_hashes = [hashlib.sha256(frame.tobytes()).hexdigest() for frame in freeze_frames]
    longest_run = 1
    current = 1
    for previous, value in zip(frame_hashes, frame_hashes[1:], strict=False):
        current = current + 1 if previous == value else 1
        longest_run = max(longest_run, current)
    assert longest_run >= 3

    # The normalized hand-region union covers the center of this crop.
    source_region = source_frames[0][20:48, 15:82]
    occluded_region = occluded_frames[0][20:48, 15:82]
    assert occluded_region.mean() < source_region.mean() * 0.2

    source_duration = probe_video(
        tmp_path / "videos" / "source.mp4", ffprobe_bin=str(FFPROBE)
    ).duration_s
    cut_duration = probe_video(
        output / by_transform["scene_cut"]["output"]["path"],
        ffprobe_bin=str(FFPROBE),
    ).duration_s
    assert cut_duration < source_duration
    assert by_transform["scene_cut"]["transformation"]["parameters"]["removed_frame_count"] > 0


def test_non_corruption_issues_require_and_inherit_source_evidence(tmp_path: Path) -> None:
    _make_source(tmp_path / "videos" / "source.mp4")
    windows = []
    for index, issue in enumerate(("no_hands", "low_hand_activity")):
        source_kind = "human" if index == 0 else "human-derived"
        label_provenance: dict[str, object] = {
            "readiness": {"kind": source_kind},
            "issues": {"kind": source_kind},
            "boundaries": {"kind": "unlabeled"},
        }
        window = {
            "start_s": float(index),
            "end_s": float(index + 1),
            "issues": {issue: True},
            "issue_valid": {issue: True},
            "readiness": "REJECT",
            "readiness_valid": True,
            "annotator": f"human-reviewer-{index}",
            "label_provenance": label_provenance,
        }
        if index == 0:
            label_provenance.update({"review_count": 3, "rubric_version": "egosieve-annotation/v1"})
        else:
            window.update({"review_count": 3, "rubric_version": "egosieve-annotation/v1"})
        windows.append(window)
    annotations = tmp_path / "source.jsonl"
    annotations.write_text(
        json.dumps(
            {
                "schema": SCHEMA_VERSION,
                "id": "reviewed-source",
                "group_id": "reviewed-session",
                "video": "videos/source.mp4",
                "license": "CC0-1.0",
                "split": "test",
                "windows": windows,
            },
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    result = build_augmented_corpus(
        annotations,
        tmp_path / "derived",
        allowed_licenses=["CC0-1.0"],
        config=AugmentationConfig(transforms=("no_hands", "low_hand_activity")),
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )

    assert result.generated_count == 2
    assert result.skipped_count == 2
    records = load_jsonl(result.annotations_path)
    assert {next(iter(record.windows[0].issues)) for record in records} == {
        "no_hands",
        "low_hand_activity",
    }
    for record in records:
        window = record.windows[0]
        assert record.group_id == "reviewed-session"
        assert record.extra["split"] == "test"
        assert window.annotator == "human-derived:egosieve.augmentation/v1"
        assert window.readiness == "REJECT"
        assert window.readiness_valid is True
        assert window.extra["review_count"] == 3
        assert window.extra["rubric_version"] == "egosieve-annotation/v1"
        provenance = window.extra["label_provenance"]
        assert provenance["readiness"]["kind"] == "human-derived"
        assert provenance["readiness"]["inheritance"] == "source_window"
        assert provenance["issues"]["kind"] == "human-derived"
        assert provenance["issues"]["inheritance"] == "source_window"
        assert provenance["issues"]["derived_reencode"] is True
        assert provenance["issues"]["source_kind"] in {"human", "human-derived"}
        assert provenance["boundaries"] == {"kind": "unlabeled"}

    provenance_rows = _read_jsonl(result.provenance_path)
    assert {row["transformation"]["label_kind"] for row in provenance_rows} == {"human-derived"}
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert manifest["counts"]["by_label_origin"] == {"human-derived": 2}
    assert manifest["counts"]["inherited_readiness"] == 2
    assert manifest["label_policy"]["human_review_fields_inherited_only_for"] == ("human-derived")


@pytest.mark.parametrize("source_provenance", ["controlled", "legacy-flat-human"])
def test_faithful_reencode_rejects_non_task_human_issue_provenance(
    tmp_path: Path,
    source_provenance: str,
) -> None:
    annotations = _write_annotations(tmp_path)
    source = json.loads(annotations.read_text(encoding="utf-8"))
    window = source["windows"][0]
    window["issues"]["no_hands"] = True
    window["issue_valid"]["no_hands"] = True
    if source_provenance == "controlled":
        window["label_provenance"]["issues"] = {"kind": "programmatic-controlled-corruption"}
    else:
        window["label_provenance"] = {"kind": "human"}
    annotations.write_text(json.dumps(source, sort_keys=True) + "\n", encoding="utf-8")

    result = build_augmented_corpus(
        annotations,
        tmp_path / "derived",
        allowed_licenses=["CC0-1.0"],
        config=AugmentationConfig(transforms=("blur", "no_hands")),
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )

    assert result.generated_count == 1
    assert result.skipped_count == 1
    generated = load_jsonl(result.annotations_path)
    assert generated[0].windows[0].issues == {"blur": True}
    assert generated[0].windows[0].extra["label_provenance"]["issues"]["kind"] == (
        "programmatic-controlled-corruption"
    )
    skipped = _read_jsonl(result.skipped_path)
    assert skipped[0]["transform"] == "no_hands"
    assert skipped[0]["code"] == "human_issue_provenance_required"


def test_output_identity_is_deterministic_across_destinations(tmp_path: Path) -> None:
    annotations = _write_annotations(tmp_path)
    config = AugmentationConfig(transforms=("blur", "freeze", "scene_cut"))
    first = build_augmented_corpus(
        annotations,
        tmp_path / "first",
        allowed_licenses=["CC0-1.0"],
        config=config,
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )
    second = build_augmented_corpus(
        annotations,
        tmp_path / "second",
        allowed_licenses=["CC0-1.0"],
        config=config,
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )

    assert first.annotations_path.read_bytes() == second.annotations_path.read_bytes()
    first_manifest = json.loads(first.manifest_path.read_text(encoding="utf-8"))
    second_manifest = json.loads(second.manifest_path.read_text(encoding="utf-8"))
    assert first_manifest["build_fingerprint"] == second_manifest["build_fingerprint"]
    first_hashes = {
        row["transformation"]["name"]: row["output"]["sha256"]
        for row in _read_jsonl(first.provenance_path)
    }
    second_hashes = {
        row["transformation"]["name"]: row["output"]["sha256"]
        for row in _read_jsonl(second.provenance_path)
    }
    assert first_hashes == second_hashes


def test_license_allowlist_is_mandatory_and_exact(tmp_path: Path) -> None:
    annotations = _write_annotations(tmp_path)
    with pytest.raises(ValueError, match="allowed_licenses"):
        build_augmented_corpus(annotations, tmp_path / "none", allowed_licenses=[])
    with pytest.raises(AugmentationError, match="not in the explicit allowed-license"):
        build_augmented_corpus(
            annotations,
            tmp_path / "wrong",
            allowed_licenses=["Apache-2.0"],
            ffmpeg_bin=str(FFMPEG),
            ffprobe_bin=str(FFPROBE),
        )
    assert not (tmp_path / "wrong").exists()


def test_occlusion_without_hand_regions_is_skipped_not_mislabeled(tmp_path: Path) -> None:
    annotations = _write_annotations(tmp_path, hand_regions=False)
    result = build_augmented_corpus(
        annotations,
        tmp_path / "derived",
        allowed_licenses=["CC0-1.0"],
        config=AugmentationConfig(transforms=("blur", "hand_occlusion")),
        ffmpeg_bin=str(FFMPEG),
        ffprobe_bin=str(FFPROBE),
    )
    assert result.generated_count == 1
    assert result.skipped_count == 1
    skipped = _read_jsonl(result.skipped_path)
    assert skipped[0]["transform"] == "hand_occlusion"
    assert skipped[0]["code"] == "hand_regions_missing"
    record = load_jsonl(result.annotations_path)[0]
    assert record.windows[0].issues == {"blur": True}
    assert "hand_occlusion" not in record.windows[0].issue_valid


def test_group_cannot_cross_preassigned_splits(tmp_path: Path) -> None:
    _make_source(tmp_path / "videos" / "source.mp4")
    records = []
    for index, split in enumerate(("train", "test")):
        records.append(
            {
                "schema": SCHEMA_VERSION,
                "id": f"source-{index}",
                "group_id": "shared-session",
                "video": "videos/source.mp4",
                "license": "CC0-1.0",
                "split": split,
                "windows": [{"start_s": 0.0, "end_s": 1.0}],
            }
        )
    annotations = tmp_path / "source.jsonl"
    annotations.write_text(
        "".join(json.dumps(record) + "\n" for record in records),
        encoding="utf-8",
    )
    with pytest.raises(AugmentationError, match="crosses source splits"):
        build_augmented_corpus(
            annotations,
            tmp_path / "derived",
            allowed_licenses=["CC0-1.0"],
            config=AugmentationConfig(transforms=("blur",)),
            ffmpeg_bin=str(FFMPEG),
            ffprobe_bin=str(FFPROBE),
        )
